hooks:
  - hooks.py

not_in_nav: |
  /plugins/legacy/*.md

site_name: ERRSA Staff Wiki
site_description: ERRSA Minecraft staff procedures, learning, tools and troubleshooting.

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.prune
    - content.tooltips
    - navigation.path
    - navigation.tracking
    - navigation.indexes
    - navigation.top
    - toc.follow
    - toc.integrate
    - search.suggest
    - search.highlight
    - search.share
    - content.code.copy

  palette:
    - scheme: slate
      primary: blue grey
      accent: cyan
      toggle:
        icon: material/weather-sunny
        name: Light mode
    - scheme: default
      primary: blue grey
      accent: light blue
      toggle:
        icon: material/weather-night
        name: Dark mode

extra_javascript:
  - assets/javascripts/wiki-editor.js
  - assets/javascripts/plugin-preview.js
  - assets/javascripts/preview-click.js
  - assets/javascripts/wiki-sync.js
  - assets/javascripts/wiki-live-pages.js
  - assets/javascripts/wiki-tag-colors.js

extra_css:
  - assets/stylesheets/extra.css
  - assets/stylesheets/permissions-model.css

plugins:
  - search
  - typeset
  - tags
  - git-revision-date-localized:
      type: date
      enable_creation_date: false
      enable_git_follow: true
      fallback_to_build_date: true
      timezone: America/New_York

markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.superfences
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Home: index.md

  - Documentation:
      - Overview: documentation/index.md
      - 1. Introduction: documentation/introduction.md
      - 2. Staff Roles & Responsibilities: documentation/staff-roles-responsibilities.md
      - 3. Standard Procedures: documentation/standard-procedures.md
      - 4. Staff Actions & Records: documentation/logging-documentation.md
      - 5. Server Versions: documentation/server-version.md
      - 6. Staff Advancement & Governance: documentation/6-staff-advancement-and-governance.md

  - Learning:
        - Overview: learning/index.md
        - Server Fundamentals:
              - Introduction: learning/fundamentals/intro.md
              - Module 1 · Understanding ERRSA MC: learning/fundamentals/mod1.md
              - Module 2 · Server Rules & Expectations: learning/fundamentals/mod2.md
              - Module 3 · Player Support: learning/fundamentals/mod3.md
              - Module 4 · In-Game Systems: learning/fundamentals/mod4.md
              - Module 5 · Communication & Staff Resources: learning/fundamentals/mod5.md
        - Moderators:
            - Introduction: learning/moderators/intro.md
            - Module 1 · Moderation Fundamentals: learning/moderators/mod1.md
            - Module 2 · Handling Player Reports: learning/moderators/mod2.md
            - Module 3 · Interpreting the Rules: learning/moderators/mod3.md
            - Module 4 · Cheating & Exploits: learning/moderators/mod4.md
            - Module 5 · Player Disputes: learning/moderators/mod5.md
            - Module 6 · Moderation Records & Disciplinary Actions: learning/moderators/mod6.md
        - Admins:
            - Coming Soon: learning/soon.md
            #- Introduction: learning/admins/intro.md
            #- Module 1 · Advanced Moderation: learning/admins/mod1.md
            #- Module 2 · Player Investigations: learning/admins/mod2.md
            #- Module 3 · Permissions & Staff Access: learning/admins/mod3.md
            #- Module 4 · Player Restoration & Recovery: learning/admins/mod4.md
            #- Module 5 · Server Administration: learning/admins/mod5.md
            #- Module 6 · Advanced Player & World Management: learning/admins/mod6.md
            #- Module 7 · Handling Major Incidents: learning/admins/mod7.md
        - Developers:
            - Coming Soon: learning/soon.md
            #- Introduction: learning/developers/intro.md
            #- Module 1 · ERRSA Server Architecture: learning/developers/mod1.md
            #- Module 2 · Plugin Management: learning/developers/mod2.md
            #- Module 3 · ERRSA Plugin Ecosystem: learning/developers/mod3.md
            #- Module 4 · Server Configuration & Files: learning/developers/mod4.md
            #- Module 5 · Databases & External Services: learning/developers/mod5.md
            #- Module 6 · Debugging & Server Troubleshooting: learning/developers/mod6.md
            #- Module 7 · Development Workflow: learning/developers/mod7.md
        - Server Lead:
            - Coming Soon: learning/soon.md
            #- Introduction: learning/lead/into.md
            #- Module 1 · Staff Leadership: learning/lead/mod1.md
            #- Module 2 · Staff Recruitment & Training: learning/lead/mod2.md
            #- Module 3 · Staff Management: learning/lead/mod3.md
            #- Module 4 · Server Operations: learning/lead/mod4.md
            #- Module 5 · Server Development & Planning: learning/lead/mod5.md
            #- Module 6 · Events & Community Management: learning/lead/mod6.md
            #- Module 7 · Major Incident Management: learning/lead/mod7.md
            #- Module 8 · Server Direction & Long-Term Planning: learning/lead/mod8.md

  - Tools:
        - Overview: tools/index.md
        - tools/discord/index.md
        - tools/github/index.md
        - tools/apex-hosting/index.md
        - tools/phpmyadmin/index.md
        - tools/power-automate/index.md
        - tools/render/index.md
        - tools/fillout/index.md
        - tools/tebex/index.md

  - Plugins:
      - Overview: plugins/index.md
      - Staff Permissions: plugins/staff-permissions.md
      - Live Server Inventory: plugins/live-inventory.md
      - template: plugins/template.md

      - Permissions And Moderation:
          - LuckPerms: plugins/permissions-and-moderation/luckperms.md
          - CoreProtect: plugins/permissions-and-moderation/coreprotect.md
          - GriefPrevention: plugins/permissions-and-moderation/griefprevention.md
          - ChatFilter: plugins/permissions-and-moderation/chatfilter.md
          - Themis: plugins/permissions-and-moderation/themis.md
          - InventoryAudit: plugins/permissions-and-moderation/inventoryaudit.md

      - Server And Infrastructure:
          - AutoUpdateGeyser: plugins/server-and-infrastructure/autoupdategeyser.md
          - ERRSA-MC-Core: plugins/server-and-infrastructure/errsa-mc-core.md
          - ERRSACompatibilityPaper: plugins/server-and-infrastructure/errsacompatibilitypaper.md
          - ERRSAWebBridge: plugins/server-and-infrastructure/errsawebbridge.md
          - EventBridge: plugins/server-and-infrastructure/eventbridge.md
          - SqlPing: plugins/server-and-infrastructure/sqlping.md
          - Essentials: plugins/server-and-infrastructure/essentials.md
          - EssentialsSpawn: plugins/server-and-infrastructure/essentialsspawn.md
          - ProtocolLib: plugins/server-and-infrastructure/protocollib.md
          - PlayerInitialization: plugins/server-and-infrastructure/playerinitialization.md
          - PlaceholderAPI: plugins/server-and-infrastructure/placeholderapi.md
          - Maintenance: plugins/server-and-infrastructure/maintenance.md
          - Tebex: plugins/server-and-infrastructure/tebex.md
          - VIPBridge: plugins/server-and-infrastructure/vipbridge.md
          - Vault: plugins/server-and-infrastructure/vault.md
          - viaVersion: plugins/server-and-infrastructure/viaversion.md
          - Hurricane: plugins/server-and-infrastructure/hurricane.md
          - Floodgate: plugins/server-and-infrastructure/floodgate.md
          - MiniMOTD: plugins/server-and-infrastructure/minimotd.md
          - TabCompleteFilter: plugins/server-and-infrastructure/tabcompletefilter.md

      - Worlds And Building:
          - Chunky: plugins/worlds-and-building/chunky.md
          - ChunkyBorder: plugins/worlds-and-building/chunkyborder.md
          - FastAsyncVoxelSniper: plugins/worlds-and-building/fastasyncvoxelsniper.md
          - FastAsyncWorldEdit: plugins/worlds-and-building/fastasyncworldedit.md
          - Multiverse-Core: plugins/worlds-and-building/multiverse-core.md
          - Multiverse-Inventories: plugins/worlds-and-building/multiverse-inventories.md
          - Multiverse-Portals: plugins/worlds-and-building/multiverse-portals.md
          - PlotSquared: plugins/worlds-and-building/plotsquared.md
          - WorldGuard: plugins/worlds-and-building/worldguard.md
          - WorldGuardExtraFlags: plugins/worlds-and-building/worldguardextraflags.md
          - Skript: plugins/worlds-and-building/skript.md
          - SkBee: plugins/worlds-and-building/skbee.md

      - Gameplay And Progression:
          - Guilds: plugins/gameplay-and-progression/guilds.md
          - PlayerQuests: plugins/gameplay-and-progression/playerquests.md
          - Rank-Progression: plugins/gameplay-and-progression/rank-progression.md
          - BannerBuilder: plugins/gameplay-and-progression/bannerbuilder.md
          - HeadDB: plugins/gameplay-and-progression/headdb.md
          - QuickShop-Hikari: plugins/gameplay-and-progression/quickshop-hikari.md
          - WarpGUI: plugins/gameplay-and-progression/warpgui.md
          - Wild: plugins/gameplay-and-progression/wild.md
          - SilkSpawners_v2: plugins/gameplay-and-progression/silkspawners-v2.md
          - DragonDropElytra: plugins/gameplay-and-progression/dragondropelytra.md
          - AutoUnlockPvPDrops: plugins/gameplay-and-progression/autounlockpvpdrops.md
          - ShulkerReroute: plugins/gameplay-and-progression/shulkerreroute.md
          - PVPToggle: plugins/gameplay-and-progression/pvptoggle.md

      - Display And Media:
          - FancyHolograms: plugins/display-and-media/fancyholograms.md
          - FancyNpcs: plugins/display-and-media/fancynpcs.md
          - Dynmap: plugins/display-and-media/dynmap.md
          - ImageFrame: plugins/display-and-media/imageframe.md
          - InvisibleFrames: plugins/display-and-media/invisibleframes.md
          - ArmorStandTools: plugins/display-and-media/armorstandtools.md
          - EssentialsChat: plugins/display-and-media/essentialschat.md
          - TAB: plugins/display-and-media/tab.md
          - AutoMessage: plugins/display-and-media/automessage.md
          - URLCustomDiscs: plugins/display-and-media/urlcustomdiscs.md
          - VoiceChat: plugins/display-and-media/voicechat.md

  - Changelog:
      - Releases: changelog/releases.md

  - Troubleshooting:
      - Overview: troubleshooting/index.md
      - Common issues: troubleshooting/common-issues.md
      - Permissions: troubleshooting/permissions.md
      - Plugin issues: troubleshooting/plugin-issues.md